config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  get 'homes/index'
  get 'results/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnose.rb
class Diagnose < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    diagnoses = Diagnose.all
    @diagnoses = diagnoses.shuffle
    @count
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(Rails.application.credentials.dig(:spotify, :client_id), Rails.application.credentials.dig(:spotify, :secret_id))

  def show
    @result = CountsForm.new(set_count_params)

    serch = ['dance','party']

    if @result.count == 0
      country = "US"
      search = "dance"
      @result_usa = RSpotify::Track.search("The Star Spangled Banner (National Anthem of the USA) [Band and Chorus Version]").first(1)
      @popular_tracks = america_popular_songs(search, country)
    elsif @result.count == 1
      country = "NP"
      search = "नृत्य"
      playlist = "नेपाल"
      @result_nepal = search_playlist(playlist)
      @popular_tracks = search_popular_songs(search, country)
    elsif @result.count == 2
      country = "TH"
      search = "เต้นรำ"
      playlist = "งานสังสรรค์"
      @result_thailand = search_playlist(playlist)
      @popular_tracks = search_popular_songs(search, country)
    elsif @result.count == 3
      country = "ZA"
      search = "afro pop"
      playlist = "partytjie"
      @result_africa = search_playlist(playlist)
      @popular_tracks = search_popular_songs(search, country)
    elsif @result.count == 4
      country = "IN"
      search = "करी"
      playlist = "नृत्य"
      @result_india = search_playlist(playlist)
      @popular_tracks = search_popular_songs(search, country)
    else
      country = "BR"
      search = "dança"
      playlist = "dança"
      @result_brazil = search_playlist(playlist)
      @popular_tracks = search_popular_songs(search, country)
    end
  end

  private

  def set_count_params
    params.permit(:count)
  end

  def search_playlist(playlist)
    country_playlist = RSpotify::Playlist.search(playlist).first(3)
    country_playlist.shuffle!
  end

  def search_popular_songs(search, country)
    popular_tracks = RSpotify::Track.search(search,  market: country).first(18) 
    popular_tracks.shuffle!
  end
2
  def america_popular_songs(search, country)
    tracks = RSpotify::Track.search(search,  market: country).first(50) 
    popular_tracks = tracks.select do |track|
    track.album.popularity > 70
    end
    popular_tracks.shuffle!
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'メンタルDJ',
      title: '診察ご案内',
      reverse: true,
      separator: '|',
      description: 'ツラい気持ちを音楽療法で和らげよう',
      keywords: 'Spotify 音楽療法 アフリカ音楽 ネパール音楽 タイ音楽 インド音楽 ブラジル音楽',
      canonical: request.original_url,
      noindex: ! Rails.env.production?,
      icon: [
        { href: image_url('abstract-doctor.png') },
        { href: image_url('abstract-doctor.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'メンタルDJ',
        title: 'メンタルDJ',
        description: 'ツラい気持ちを音楽療法で和らげよう', 
        type: 'website',
        url: request.original_url,
        image: image_url('abstract-doctor.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@jiffu_fu',
      }
    }
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/homes/index.html.erb
<div class="main-content">
</div>
<br>
<h1 class="card">👈 　NO　🤔　YES 👉</h1>
<br>
<div id="tinderslide" class="container-fluid flex">
  
  <ul>
    <% @diagnoses.each do |diagnose| %>
    
      <li data-diagnoses="<%= diagnose.text %>">
        <div class="diagnoseText"><%= diagnose.text %></div>
        <%= image_tag diagnose.image, class: "img-fluid diagnose-image" %>
        <div class="like"></div>
        <div class="dislike"></div>
        
      </li>
    <% end %>
  </ul>
  <%= form_with url: results_show_path, method: :get, local: true do |f| %>
  <%= f.number_field :count, id: "count", value: 0, min: 0, max: 5 %>
  <%= f.submit("", class: "noUser", id: "submit") %>
  <% end %>
</div>
<% set_meta_tags title: "診察中" %>


<script>
  // スワイプするユーザー数の定数を定義
  var usersNum = 5
  var currentUserIndex = 0;
  var countUp = 0;
  var countLike = 0;
  var postReaction = function (diagnoses_id, reaction) {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
        }
    });
    
  }
  $("#tinderslide").jTinder({
    onDislike: function (item) {
      currentUserIndex++;
      checkUserNum();
      var diagnoses_id = item[0].dataset.diagnoses_id
      postReaction(diagnoses_id, 'dislike')
    },
    onLike: function (item) {
      currentUserIndex++;
      var diagnoses_id = item[0].dataset.diagnoses_id
      postReaction(diagnoses_id, 'like')
      // addLike++;
      // console.log(countLike);
      // console.log($("#count").val('') = Number(countLike));
      
      // $('#count').val(Number(countLike));
      // $("#count").val('') = Number(countLike);
      // console.log(countLike);
      // console.log($("#count").val('') = Number(countLike));
      ++countLike;
      $("#count").val(String(countLike));
      checkUserNum();
      // var valText = $('#count').defaultValue;
      // var val = Number(countLike) || 0;  // NaNのとき0にする
      
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  

  function checkUserNum() {
    // スワイプするユーザー数とスワイプした回数が同じになればaddClassする
    if (currentUserIndex === usersNum){
      $(".noUser").addClass("is-active");
      // $("#count").value = addLike;
      $("#submit").click();
      return;
    }
  };

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= display_meta_tags (default_meta_tags) %>
  </head>

<body>
  <%= render 'shared/header' %>
  <%= yield %>
</body>
</html>

app/views/layouts/results.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>診察結果</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'results', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/results/_africa.html.erb
<%= render 'shared/header' %>
<div class="africa-image">

<div class="top-wrapper">
  <div class="africa">
    <h1 class="result display-1 text-center">🤖診断結果🤖</h1>
    <br>
    <br>
    <p class="h2 stroke description text-center font-weight-bold">５問中、３問にYESと答えたあなた！<br>👨‍🔬安定した精神状態です！<br></p><br>
    <p class="h3 stroke-2 description text-center font-weight-bold">アフリカの素敵なことわざと、強靭でグルーヴィーな音楽をどうぞ！</p>
    <div class="row tweet justify-content-center">
      <button onclick="tweet()" class="btn btn-info btn-lg mt-10">Tweetする</button>
    </div>
    <div class="row tweet justify-content-center">
      <%= link_to "再診はコチラから", homes_index_path, method: :get, class: 'btn btn-primary btn-lg active btn-link' %>
    </div>
    <div class="blank-2"></div>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <p class="h2 stroke-3 present text-center">"ゆっくりゆっくり バナナは熟れる"</p>
    <p class="h5 stroke-4 present text-center">成熟した人間になるには時間がかかるという意</p><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
  </div>
  <div class="blank"></div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <p class="h1 description text-center stroke-2">🇿🇦南アフリカを堪能する！🇿🇦<br>🇿🇦プレイリストたち！🇿🇦</p>
          <br><br>
          <% result.each do |track| %>
            <p class="h5 mt-lg-3 playlist-name text-center stroke-3">プレイリスト名： <%= track.name %></p>
            <div class="embed-responsive embed-responsive-4by3"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/playlist/<%= track.id %>?utm_source=generator" width="100%" height="300" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
      </div>
    </div>
    <br><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <div class="bkank-2"></div>

    <div class="track-name">
      <p class="lead-1 description stroke-2">🇿🇦南アフリカが誇る！🇿🇦<br>🇿🇦パーティーソングたち！🇿🇦</p>
      <p class="h2 set-3 stroke-3">👨‍🔬＜カラダを動かそう！リズムに合わせて！</p>
        <div class="row justify-content-center">
          <% popular_tracks.each do |track| %>

            <br>
            <div class="col-4 m-4 embed-responsive embed-responsive-1by1"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/track/<%= track.id %>?utm_source=generator" width="90%" height="" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
        </div>
    </div>

  </div>
</div>

</div>

<% set_meta_tags title: "アフリカ" %>

<script>
function tweet() {
  const dataText = '\nツラい気持ち診断をしたところ、アフリカのノリノリな音楽を処方されました！'
  const dataUrl = 'https://mental-dj.herokuapp.com/'
  const dataVia = 'jiffu_fu'
  const dataHashtags = 'メンタルDJ' + '&hashtags=個人開発' + '&hashtags=クソアプリ'

  window.open(
    'https://twitter.com/intent/tweet?&text=' +
      dataText +
      '%0a&' +
      '%0a&' +
      '&url=' +
      dataUrl +
      '%0a&' +
      '&via=' +
      dataVia +
      '&hashtags=' +
      dataHashtags
  )
}

</script>

app/views/results/_brazil.html.erb
<%= render 'shared/header' %>
<div class="brazil-image">

<div class="top-wrapper">
  <div class="brazil">
    <h1 class="result display-1 text-center">🤖診断結果🤖</h1>
    <br>
    <br>
    <p class="h2 stroke description text-center font-weight-bold">５問全てにYESと答えたあなた！<br>とても良好な精神状態です！<br></p><br>
    <p class="h3 stroke-2 description text-center font-weight-bold">ブラジルの有名なことわざと、アゲアゲでスパイシィな音楽をどうぞ！</p>
    <div class="row tweet justify-content-center">
      <button onclick="tweet()" class="btn btn-info btn-lg mt-6">Tweetする</button>
    </div>
    <div class="row tweet justify-content-center">
      <%= link_to "再診はコチラから", homes_index_path, method: :get, class: 'btn btn-primary btn-lg active btn-link' %>
    </div>
    <div class="blank-2"></div>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <p class="h2 stroke-3 present text-center">"Quem canta, seus males espanta!"</p>
    <p class="h5 stroke-4 present text-center">「歌う人は、災いを遠ざける」</p><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>

  </div>
  <div class="blank"></div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <p class="h1 description text-center stroke-2">🇧🇷ブラジルを堪能する！🇧🇷<br>🇧🇷プレイリストたち！🇧🇷</p>
          <br><br>
          <% result.each do |track| %>
            <p class="h5 mt-lg-3 playlist-name text-center stroke-3">プレイリスト名： <%= track.name %></p>
            <div class="embed-responsive embed-responsive-4by3"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/playlist/<%= track.id %>?utm_source=generator" width="100%" height="300" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
      </div>
    </div>
    <br><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <div class="bkank-2"></div>

    <div class="track-name">
      <p class="lead-1 description stroke-2">🇧🇷ブラジルが誇る！🇧🇷<br>🇧🇷パーティーソングたち！🇧🇷</p>
      <p class="h2 set-1 stroke-3">💃＜皆で踊ろう！カラダがおかしくなるまで！</p>
      <p class="h2 set-3 stroke-3">👨‍🔬＜ポジティブのその先へ！プルス・ポジティブ！</p>
        <div class="row justify-content-center">
          <% popular_tracks.each do |track| %>

            <br>
            <div class="col-4 m-4 embed-responsive embed-responsive-1by1"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/track/<%= track.id %>?utm_source=generator" width="90%" height="" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
        </div>
    </div>

  </div>
</div>

</div>

<% set_meta_tags title: "ブラジル" %>

<script>
function tweet() {
  const dataText = '\nツラい気持ち診断をしたところ、ブラジルの情熱的なパーティーソングを処方されました！'
  const dataUrl = 'https://mental-dj.herokuapp.com/'
  const dataVia = 'jiffu_fu'
  const dataHashtags = 'メンタルDJ' + '&hashtags=個人開発' + '&hashtags=クソアプリ'

  window.open(
    'https://twitter.com/intent/tweet?&text=' +
      dataText +
      '%0a&' +
      '%0a&' +
      '&url=' +
      dataUrl +
      '%0a&' +
      '&via=' +
      dataVia +
      '&hashtags=' +
      dataHashtags
  )
}

</script>

app/views/results/_india.html.erb
<%= render 'shared/header' %>
<div class="india-image">

<div class="top-wrapper">
  <div class="india">
    <h1 class="result display-1 text-center">🤖診断結果🤖</h1>
    <br>
    <br>
    <p class="h2 stroke description text-center font-weight-bold">５問中、４問にYESと答えたあなた！<br>かなり良好な精神状態です！<br></p><br>
    <p class="h3 stroke-2 description text-center font-weight-bold">インドの有名なことわざと、ボヘミアンでアガる音楽をどうぞ！</p>
    <div class="row tweet justify-content-center">
      <button onclick="tweet()" class="btn btn-info btn-lg mt-6">Tweetする</button>
    </div>
    <div class="row tweet justify-content-center">
      <%= link_to "再診はコチラから", homes_index_path, method: :get, class: 'btn btn-primary btn-lg active btn-link' %>
    </div>
    <div class="blank-2"></div>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <p class="h2 stroke-3 present text-center">"牛乳があるのにバターを探す"</p>
    <p class="h5 stroke-4 present text-center">「手間を惜しんではならない」という意</p><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>

  </div>
  <div class="blank"></div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <p class="h1 description text-center stroke-2">🇮🇳インドを堪能する！🇮🇳<br>🇮🇳プレイリストたち！🇮🇳</p>
          <br><br>
          <% result.each do |track| %>
            <p class="h5 mt-lg-3 playlist-name text-center stroke-3">プレイリスト名： <%= track.name %></p>
            <div class="embed-responsive embed-responsive-4by3"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/playlist/<%= track.id %>?utm_source=generator" width="100%" height="300" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
      </div>
    </div>
    <br><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <div class="bkank-2"></div>

    <div class="track-name">
      <p class="lead-1 description stroke-2">🇮🇳インド〜〜！パーティー！ソーング！🇮🇳</p>
      <p class="h2 set-1 stroke-3">💃＜レッツパーリィ</p>
      <p class="h2 set-3 stroke-3">👨‍🔬＜悩みをなくすコツは、悩む時間で踊ることさ</p>
        <div class="row justify-content-center">
          <% popular_tracks.each do |track| %>

            <br>
            <div class="col-4 m-4 embed-responsive embed-responsive-1by1"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/track/<%= track.id %>?utm_source=generator" width="90%" height="" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
        </div>
    </div>

  </div>
</div>

</div>

<% set_meta_tags title: "インド" %>

<script>
function tweet() {
  const dataText = '\nツラい気持ち診断をしたところ、インドの陽気な音楽を処方されました！'
  const dataUrl = 'https://mental-dj.herokuapp.com/'
  const dataVia = 'jiffu_fu'
  const dataHashtags = 'メンタルDJ' + '&hashtags=個人開発' + '&hashtags=クソアプリ'

  window.open(
    'https://twitter.com/intent/tweet?&text=' +
      dataText +
      '%0a&' +
      '%0a&' +
      '&url=' +
      dataUrl +
      '%0a&' +
      '&via=' +
      dataVia +
      '&hashtags=' +
      dataHashtags
  )
}

</script>

app/views/results/_nepal.html.erb
<%= render 'shared/header' %>
<div class="nepal-image">

<div class="top-wrapper">
  <div class="nepal">
    <h1 class="result display-1 text-center">🤖診断結果🤖</h1>
    <br>
    <br>
    <p class="h2 stroke description text-center font-weight-bold">５問中、１問にYESと答えたあなた！<br>かなり落ち込み気味かも・・・<br></p><br>
    <p class="h3 stroke-2 description text-center font-weight-bold">ネパールの勇気の出ることわざと、ネパリーでブゥードゥーな音楽をどうぞ！</p>
    <div class="row tweet justify-content-center">
      <button onclick="tweet()" class="btn btn-info btn-lg mt-6">Tweetする</button>
    </div>
    <div class="row tweet justify-content-center">
      <%= link_to "再診はコチラから", homes_index_path, method: :get, class: 'btn btn-primary btn-lg active btn-link' %>
    </div>
    <div class="blank-2"></div>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <p class="h2 stroke-3 present text-center">"न बिराउनु न डराउनु"</p>
    <p class="h5 stroke-4 present text-center">「正しいことをするなら、心配する必要はない。」</p><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>

  </div>
  <div class="blank"></div>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <p class="h1 description text-center stroke-2">🇳🇵ネパールで踊れる！🇳🇵<br>🇳🇵プレイリストたち！🇳🇵</p>
          <br><br>
          <% result.each do |track| %>
            <p class="h5 mt-lg-3 playlist-name text-center stroke-3">プレイリスト名： <%= track.name %></p>
            <div class="embed-responsive embed-responsive-4by3"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/playlist/<%= track.id %>?utm_source=generator" width="100%" height="300" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
      </div>
    </div>
    <br><br>
    <p class="h6 present text-center">- * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - * - </p>
    <div class="bkank-2"></div>

    <div class="track-name">
      <p class="lead-1 description stroke-2">🇳🇵ネパール！！パーティーソング！！🇳🇵</p>
      <p class="h2 set-1 stroke-3">💃＜ネパール人は踊りが大好き</p>
      <p class="h2 set-3 stroke-3">👨‍🔬＜踊るとセロトニン・ドーパミン・オキシトンが分泌されます。</p>
        <div class="row justify-content-center">
          <% popular_tracks.each do |track| %>

            <br>
            <div class="col-4 m-4 embed-responsive embed-responsive-1by1"> 
              <iframe  style="border-radius: 2% 2% / 2% 2%;" src="https://open.spotify.com/embed/track/<%= track.id %>?utm_source=generator" width="90%" height="" frameBorder="1" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
            </div>
            <br>
          <% end %>
        </div>
    </div>

  </div>
</div>

</div>

<% set_meta_tags title: "ネパール" %>

<script>
function tweet() {
  const dataText = '\nツラい気持ち診断をしたところ、ネパールの音楽を処方されました！'
  const dataUrl = 'https://mental-dj.herokuapp.com/'
  const dataVia = 'jiffu_fu'
  const dataHashtags = 'メンタルDJ' + '&hashtags=個人開発' + '&hashtags=クソアプリ'

  window.open(
    'https://twitter.com/intent/tweet?&text=' +
      dataText +
      '%0a&' +
      '%0a&' +
      '&url=' +
      dataUrl +
      '%0a&' +
      '&via=' +
      dataVia +
      '&hashtags=' +
      dataHashtags
  )
}

</script>

app/views/static_pages/top.html.erb
<main>
  <div class="bg_pattern Circles">
  <div class="top-pages p-2">
    <h1 class='top-message pb-6 mx-auto text-xl-center stroke'>はじめまして<br>Mr.メンタルDJ博士です</h1>
  </div>

  <div class='top_man p-2 mg-thumbnail'>
    <%= image_tag 'abstract-doctor.png', class: 'mx-auto d-block doctor'%>
    
  </>
  </div>
  <br>
  <br>
  <br>
  <br>
  <div class="mx-auto">
    <h1 class='message text-xl-center'>あなたのツラいお気持ち、<br>音楽の力で癒してみませんか？</h1>
    <br>
    <br>
  </div>
  <p class="mx-auto text-xl-center how-to stroke-3">簡単な質問に５つお答えください。<br>あなただけの診察結果をお届けいたします。<p>

  <br>
  <div class="columns m-6 sticky-top text-xl-center start-button">
    <%= link_to homes_index_path, method: :get, class: 'column is-6 is-offset-3 custom-btn btn-1 submit-button button top-btn nav-link' do %>
      <span stroke-2><%= "＜＜診断を始める＞＞" %></span>
    <% end %>
  </div>
</main>

<script>
$(function () {
  if (window.matchMedia('(max-width: 768px)').matches) {
    //ここにスマホ・タブレットの時のjs
  } else {
    //ここにPCの時のjs
    const moons = ['🕐😊...........💣', '🕑😜..........💣', '🕒😁.........💣', '🕓🥱........💣', '🕔🥴.......💣', '🕕🤔......💣', '🕖😟.....💣', '🕗😨....💣', '🕘😭...💣', '🕙🤮..💣', '🕚🥺.💣', '💥💥💥💥💥💥💥💥💥💥', '💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥', '💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥', '😇GAME_OVER😇', '😇GAME_OVER😇', '🍺そんなに悩まんでもええんやで🍺', '🍺🍺そんなに悩まんでもええんやで🍺🍺', '🍺🍺そんなに悩まんでもええんやで🍺🍺', '🍺🍺そんなに悩まんでもええんやで🍺🍺', '🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺', '🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺', '🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺', '🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺', '🍺🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺🍺', '🍺🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺🍺', '🍺🍺🍺🍺そんなに悩まんでもええんやで🍺🍺🍺🍺','＼＼＼＼＼＼そんなに悩まんでもええんやで／／／／／／', '＼＼＼＼＼＼そんなに悩まんでもええんやで／／／／／／'];
    let count = 0;
    setInterval(()=> {
    location.hash = moons[count % moons.length];
    count++;
}, 2000);
  }
})
</script>